### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by fileung** [PacktPublishing/Hands-On-Generative-Adversarial-Networks-with-Keras#2]
Hi,
In some chapters, in section Technical requirements 
the link to the Docker container is missing/not available?
https://github.com/packt/hands_on_gans_with_keras/blob/master/Dockerfile
https://github.com/rafaelvalle/hands_on_gans_with_keras/blob/master/Dockerfile

**Comment by fabiobento** [comment]
Hi,
Same problem here.
This book mention a Docker container that would be at : https://github.com/rafaelvalle/hands_on_gans_with_keras/blob/master/Dockerfile, however the page is not available (error 404).

**Comment by rafaelvalle** [comment]
https://github.com/PacktPublishing/Hands-On-Generative-Adversarial-Networks-with-Keras/blob/master/Dockerfile
