### ISSUE TITLE
chapter 7 - GAN model training error

### ISSUE THREAD

**Issue by fileung** [PacktPublishing/Hands-On-Generative-Adversarial-Networks-with-Keras#4]
Hi,
In chapter 7 - Progressive Growing of GANs
I have used the default code and settings, no changes.
In terminal:
$python3 train.py
model training for several hours, then error occurred. 

.......
iter 343747 cur_block 0.0 lr 0.001 kimg 5499.952 losses_d [-923.39386, -1826.8832, 28.22277, 621261.6] loss_g 1557.2732
iter 343748 cur_block 0.0 lr 0.001 kimg 5499.968 losses_d [-808.98425, -1293.4147, 32.072624, 163704.14] loss_g 2303.7917
iter 343749 cur_block 0.0 lr 0.001 kimg 5499.984 losses_d [-1013.25415, -1862.898, 30.708475, 542559.06] loss_g 2311.691
Traceback (most recent call last):
  File "train.py", line 161, in <module>
    train()
  File "train.py", line 104, in train
    batch_size = MINIBATCH_OVERWRITES[phase_idx]
KeyError: 6

Also the loss_g and losses_d is extremely high? am i missing something?
I have run some other GAN model training in the same machine and it works fine.
Thanks,

**Comment by rafaelvalle** [comment]
You probably trained the model for too long, leading to instability. 
The model in this chapter should start producing good results around 20k iterations.
Take a look at samples generated at 20k iterations and let us know.

**Comment by fileung** [comment]
Thanks for the reply.
I have viewed the fake images in tensorboard images tab, the last batch of fake images at around iteration 300,000 looks good (have fine detail) even at the end of the training where the losses were very high and the exception occurred. 
The images at iteration 20,000 looked very 'pixely' in my result, not as good. 
I have only trained the model for 6 hours on RTX 2070 8GB.
I expected Progressive GAN need more time on training, but maybe because the resolution is only 32x32 (default) so it needs only a few hours. Last time i just assumed the model training failed as exception occurred.
I will need a different dataset to train on a higher resolution as cifar10 images are 32x32.

**Comment by rafaelvalle** [comment]
Great to hear that in 6 hours you were able to get good results. 
Yes, Progressive Growing of GANs takes more time to train on high resolution images.
In the book we show an example on 32 by 32 images such that people can obtain results quickly, still being able to train models on higher resolution images.
